"""Zentrale Gestaltungseinstellungen für das Kontaktbuch."""

# Farben
FARBE_HINTERGRUND = "#F3F4F6"
FARBE_KARTE = "#FFFFFF"
FARBE_PRIMAER = "#2563EB"
FARBE_PRIMAER_AKTIV = "#1D4ED8"
FARBE_ERFOLG = "#16A34A"
FARBE_ERFOLG_AKTIV = "#15803D"
FARBE_WARNUNG = "#D97706"
FARBE_WARNUNG_AKTIV = "#B45309"
FARBE_GEFAHR = "#DC2626"
FARBE_GEFAHR_AKTIV = "#B91C1C"
FARBE_TEXT = "#1F2937"
FARBE_TEXT_HELL = "#6B7280"
FARBE_RAND = "#D1D5DB"
FARBE_AUSWAHL = "#DBEAFE"

# Schriftarten
SCHRIFT_TITEL = ("Segoe UI", 22, "bold")
SCHRIFT_UNTERTITEL = ("Segoe UI", 13, "bold")
SCHRIFT_NORMAL = ("Segoe UI", 11)
SCHRIFT_KLEIN = ("Segoe UI", 9)
SCHRIFT_BUTTON = ("Segoe UI", 10, "bold")

# Abstände
ABSTAND_KLEIN = 5
ABSTAND_NORMAL = 10
ABSTAND_GROSS = 20

# Fenster
FENSTER_TITEL = "Mein Kontaktbuch"
FENSTER_BREITE = 1000
FENSTER_HOEHE = 650
FENSTER_MIN_BREITE = 850
FENSTER_MIN_HOEHE = 550